#!/usr/bin/env bash
# 0-change_your_home_IP: modifies the /etc/host file to reroute requests
# to localhost domain to 127.0.0.2 and facebook.com to 8.8.8.8

less /etc/hosts | cat | grep -Ev "[ 	]+localhost[ 	]*" > ~/hosts
echo "127.0.0.2   localhost" >> ~/hosts
echo "8.8.8.8     facebook.com" >> ~/hosts
cp -f ~/hosts /etc/hosts
